### PR TITLE
support creation of procs from files and allow passing arguments to new procs

### PR DESCRIPTION
**Pull request by catwell**
This PR adds two features to newproc() :

- the ability to create procs from files instead of strings;
- the ability to pass arguments to new procs (available in `...`).

Typically I use the second one to pass the name of a channel on which the new proc should listen.

### CODE REVIEW

**Comment by askyrme** [comment]
Thanks for your suggestions.

However, creating new Lua processes from files can easily be done in Lua by using something like: luaproc.newproc("loadfile('f.lua')()"). This way luaproc's code and API remain simpler (in particular with regards to the newproc function).

As for passing arguments on process creation, it was not clear how exactly you accessed arguments from within the newly created processes - can you provide a full working example? Anyway, doing so kind of violates a strong premise in luaproc: Lua processes must be independent from each other and can only communicate thru message passing. When you move values between states during process creation you are essentially allowing them to communicate.

**Comment by catwell** [comment]
Sorry for never answering here, I did not notice you had answered.

Regarding passing values at process creation, I used this mostly to pass the name of a channel the new process should use to communicate. The idea behind both features was to find a way to write "generic" procs that could be reused in several projects, that could (possibly) be instantiated several times, etc.

Here is a (simple but not very useful) [example](https://gist.github.com/catwell/918659f8179ad843c968) of what I mean.

**Comment by catwell** [comment]
... and with the newest version of the library I can now use the proc file from the first example like this:

```
local my_load = function(fn, chan)
    return function() assert(loadfile(fn))(chan) end
end

luaproc.newproc(my_load("gmap.proc.lua", "gmap"))
```

This does exactly what I wanted :)

**Comment by askyrme** [comment]
A nice side-effect from the latest changes. Glad they helped you. :-)

**Pull request closed without merging**
